### ISSUE TITLE
User get permission error with 0.7.6

### ISSUE THREAD

**Issue by caerandir** [superseva/sound-link#2]
Hi superseva,
tried to use your module with Foundry 0.7.6 - when a user clicks the play button in a journal entry, the message "User XY lacks permission to update PlaylistSounds in parent <CryticCode>" is displayed and nothig plays. I tried all kinds of permission changes, but cannot make it work. Any tipps?
Thanks for the work!
Caerandir

**Comment by superseva** [comment]
Hi Caerandir,
I am not sure players can trigger playlist sounds in Foundry VTT. Only GM can. I guess a 'player' tries to trigger a sound link in your game, is that correct ?

**Comment by caerandir** [comment]
Yes, exactly. Actually, I was hoping that I could use your plugin to create Journal entries the users could listen to at their own discretion. I think this is even more difficult than I expected - it seems that the audio is audible for all players, so what I would need would be a possibility to have selectivly played audio...
I guess I can help myself, since I run Foundry at my Webhoster, and it is rather easy for me to embed an audio file stored on the same webserver, but for self-hosted Foundry such a module would be really handy!

**Comment by superseva** [comment]
You could use AudioPlayer.play method for them to play the sound but that sound will not appear in the playlist player, so no volume controls for specific sound or stop button will be available in UI for that sound.
Something like:
AudioHelper.play({src: "my-music-folder/music/song.mp3", volume: 0.1, autoplay: true, loop: false}, true);

**Comment by caerandir** [comment]
Just tried to enter in a journal an \<audio controls src="path/to/audio.mp3" style="width:100%">\</audio> HTML element, and it works nice! /path/to/audio.mp3 is the same path you'd use in AudioPlayer.play, so I suppose that would even work self-hosted. I guess: Problem solved, issue closed!
