### ISSUE TITLE
Anyway to play a whole playlist?

### ISSUE THREAD

**Issue by MisterHims** [superseva/sound-link#3]
(Sorry this is not necessarily an issue but rather a suggestion.)
Hi! Thank you for this very useful little module! I was wondering if it was possible to make it play a whole playlist and not just a sound. Thank you :)

**Comment by superseva** [comment]
the thing is this mod only provides the way to call "The Furnace" module that actually plays the audio.
I might rework that after we see what audio API updates Foundry 0.8 will release, but for now I am not sure if Furnace plays 'playlists' with it's macros

**Comment by MisterHims** [comment]
Seems to make sense. Thank you for your answer :)
