### ISSUE TITLE
Sound link overwrites any @ request

### ISSUE THREAD

**Issue by ironmonk108** [superseva/sound-link#6]
I have a handful of other enrichment links that also start with an @ symbol and they all get overwritten by Sound Link.

`const sPos = text.indexOf('@');` should be changed to `const sPos = text.indexOf('@Sound');` to avoid other modules that might be adding their own enrichment tags.

**Comment by superseva** [comment]
it took me a month to just change a variable. I should really think over my real life chaos :)
I pushed the update. Thanks for the suggestion
